---
title: "CRF"
author: "Xu Zhang"
date: "2026-01-31"
output: html_document
---

```{r CRF model fitting, echo = TRUE, eval = TRUE, message=TRUE, warning=TRUE}
set.seed(123) # esnures that we can reproduce results
forest = cforest(Response ~ Time_num + log_NP_Length +NP_Concreteness + NP_Definiteness + NP_Givenness +Structural_Priming + Genre + Imperative_conditional + le + Numeric_Classifier, data = PV_data)

#### calculate variable importance ranking, takes some time
forest.varimp = varimp(forest, conditional = FALSE) 

#### since Somers'D only works with binary responses,so we use ROC curve (see Hand&Till 2001) to replace C-value. The multiclass AUC is the average of all pairwise AUC.
##get predicted probabilities for all response classes
probs<-do.call(rbind, treeresponse(forest) )

##computing multiclass AUC using pROC
install.packages("pROC")
library(pROC) 

y<-PV_data$Response
y<-factor(y)
##before assessing AUC, we need to correct the name of porbs matrix to prevent mismatch. CRF tends to rename responses
colnames(probs) <- levels(y)
## now calculating pairwise ROC
levels_y <- levels(y) 
roc_list <- list() 
for (i in 1:(length(levels_y)-1)) { 
  for (j in (i+1):length(levels_y)) { 
    class_i <- levels_y[i] 
    class_j <- levels_y[j] 
    # subset data for the two classes 
    idx <- y %in% c(class_i, class_j) 
    # binary response for this pair 
    y_bin <- factor(y[idx] == class_i, levels = c(FALSE, TRUE)) 
    # probability of class_i 
    p_i <- probs[idx, class_i] 
    roc_list[[paste(class_i, class_j, sep = "_vs_")]] <- roc(y_bin, p_i) 
  } 
}

##plotting ROC objects
plot(roc_list[[1]]) 
plot(roc_list[[2]], add = TRUE, col = "blue") 
plot(roc_list[[3]], add = TRUE, col = "red")

```

##model evaluation

```{r H&T multiclass AUC, echo=TRUE, eval=TRUE}
##computing pairwise AUCs
sapply(roc_list, auc)

##computing Hand & Till multiclass AUCs
pairwise_auc <- sapply(roc_list, auc) 
multiclass_auc <- mean(pairwise_auc) 
multiclass_auc
```

## Plotting CRF


```{r CRF plotting, fig.cap="Figure 5: Factor importance ranking" ,echo = TRUE, eval = TRUE, fig.width=6 fig.height=4}
dotplot(sort(forest.varimp), xlab="Variable Importance", panel = function(x,y){
  panel.dotplot(x, y, col='darkblue', pch=16, cex=1.1)
  panel.abline(v=abs(min(forest.varimp)), col='red',
               lty='longdash', lwd=2)
}
) 
```

##ploting without length
Since log_NP_length dominates the importance ranking to a great degree, the tree is severally compressed leaving the other predictors marginal and their importance non-interpretable. To better understand the importance of the other variables, we plot the importance without NP_length.
```{r Importance ranking without NP_length, echo=TRUE, eval=TRUE}
top_var<-names(which.max(forest.varimp))
imp_others<-forest.varimp[ names(forest.varimp) !=top_var ]
dotplot(sort(imp_others), xlab="Variable Importance (without NP_length)", panel = function(x,y){
  panel.dotplot(x, y, col='darkblue', pch=16, cex=1.1)
  panel.abline(v=abs(min(forest.varimp)), col='red',
               lty='longdash', lwd=2)
}
) 
```

